### ISSUE TITLE
queryEntities does not do appropriate return checking

### ISSUE THREAD

**Issue by towo** [schlauerlauer/gnome-shell-home-assistant#1]
Well, this is a bit of a two-fold issue, really. The actual problem is that you can't adjust settings to define the HA URL because the settings dialog can't be built.

Trying to open the settings after a fresh install, it doesn't work. Log:

```
TypeError: message is null

Stack trace:
  queryEntities@/home/twolter/.local/share/gnome-shell/extensions/homeassistant@schlauerlauer.de/prefs.js:286:5
  buildPrefsWidget@/home/twolter/.local/share/gnome-shell/extensions/homeassistant@schlauerlauer.de/prefs.js:186:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Judging by [the relevant line](https://github.com/schlauerlauer/gnome-shell-home-assistant/blob/9775b37f92e6e532e2a65fc35085b8c95c2d592a/homeassistant%40schlauerlauer.de/prefs.js#L286), I'm assuming that message is just an empty object because the query can't return anything. So I'm guessing the best fix here would be to do a "if message is not null &lt;usual behaviour&gt; else &lt;empty list&gt;".

**Comment by schlauerlauer** [comment]
Thanks for your issue.
This should be fixed with 9080dcb7d3669ff0c0c5911db8e4685f7d23ee0c
